name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format code
        run: deno fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint code
        run: deno lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run tests
        run: deno test -A --permit-no-files --coverage '**/*_test.ts'

      - name: Upload lcov report
        uses: actions/upload-artifact@v4
        with:
          name: lcov-report
          path: coverage/lcov.info

  publish:
    runs-on: ubuntu-latest
    needs: [format, lint, test]
    if: github.repository == 'plattformsen/fui' && github.event_name == 'push' && startsWith(github.ref, 'refs/branches/main')
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish package(s) dry run
        run: deno publish --dry-run

      - name: Publish package(s)
        run: deno publish
